Experiment/urls.py
from django.conf.urls import patterns, include

import settings

urlpatterns = patterns('',
    (r'^%s/' % settings.SUB_SITE, include('Experiment.urls_subsite')),
)

stock/urls.py
from django.conf.urls import patterns, include, url
from stock.views import *

login_url = '/stock/admin'

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    
    url(r'^market$', MarketView.as_view(), name='market_base'),
    url(r'^market/(?P<game_pk>\d+)$', MarketView.as_view(), name='market'),
    url(r'^market/(?P<game_pk>\d+)/table$', MarketTabularView.as_view(), name='market_tabular'),
    url(r'^market/(?P<game_pk>\d+)/(?P<stock>\w+)$', MarketScoreView.as_view(), name='market_score'),
    
    url(r'^client$', ClientView.as_view(), name='client'),
    url(r'^client/portfolio$', ClientPortfolioView.as_view(), name='client_portfolio'),
    
    url(r'^admin$', AdminView.as_view(), name='admin'),
    url(r'^admin/game$', login_required(AdminGameListView.as_view(), login_url=login_url), name='admin_game_list'),
    url(r'^admin/game/create$', login_required(AdminGameCreateView.as_view(), login_url=login_url), name='admin_game_create'),
    url(r'^admin/game/(?P<game_pk>\d+)/edit$', login_required(AdminGameEditView.as_view(), login_url=login_url), name='admin_game_edit'),
    
    url(r'^api/admin/game$', AdminApiView.as_view(), name='api_admin'),
    url(r'^api/admin/game/active$', AdminActiveGameApiView.as_view(), name='api_admin_active'),
    url(r'^api/admin/game/(?P<game_pk>\d+)/portfolio$', login_required(AdminPortfolioApiView.as_view(), login_url=login_url), name='api_admin_portfolio'),
    url(r'^api/admin/game/(?P<game_pk>\d+)/(?P<action>\w+)', login_required(AdminGameApiView.as_view(), login_url=login_url), name='api_admin_game'),
    
    url(r'^api/market/(?P<game_pk>\d+)$', MarketApiView.as_view(), name='api_market'),
      
    url(r'^api/client/portfolio$', ClientPortfolioApiView.as_view(), name='api_client_portfolio'),
    url(r'^api/client/portfolio/(?P<order_pk>\d+)$', ClientPortfolioCancelApiView.as_view(), name='api_client_portfolio_cancel'),  
)

stock/models.py
from django.db import models, transaction, connection
from json.encoder import JSONEncoder
import datetime
import string
from decimal import Decimal
from django.db.models.aggregates import Sum
from django.db.models.query_utils import Q

class GameException(Exception):
    def __init__(self, message):
        self.message = message
        
    def __str__(self):
        return repr(self.message)

class GameManager(models.Manager):
    
    def get_active_game(self):
        return self.get_query_set().filter(end__isnull=True).exclude(end_target__lte=datetime.datetime.now())
    
    def get_history(self):
        return self.get_query_set().filter(Q(end__isnull=False) | Q(end_target__lte=datetime.datetime.now()))

class Game(models.Model):
    
    STOCK_LIST = [c for c in string.uppercase[:10]] 
    
    READY = 1
    RUNNING = 2
    END = 3
    
    name = models.CharField(max_length=100, blank=True)
    password = models.CharField(max_length=50, unique=True)
    init_price = models.DecimalField(decimal_places=2, max_digits=7, default=Decimal(100))
    init_qty = models.PositiveIntegerField(default=10)
    init_cash = models.DecimalField(decimal_places=2, max_digits=12, default=Decimal(1000))
    period = models.PositiveIntegerField(default=15)  # minutes

    start = models.DateTimeField(blank=True, null=True)
    end = models.DateTimeField(blank=True, null=True)
    end_target = models.DateTimeField(blank=True, null=True)
    
    objects = GameManager()
    
    class Meta:
        ordering = ['-pk']
    
    @property
    def state(self):
        if self.start is None:
            return Game.READY
        elif self.end is None and self.end_target > datetime.datetime.now():
            return Game.RUNNING
        else:
            return Game.END

    @transaction.commit_on_success
    def start_game(self):
        if self.state == Game.READY:
            self.start = datetime.datetime.now()
            self.end_target = self.start + datetime.timedelta(minutes=self.period)
            self.save()
            
            for p in self.portfolio_set.all():
                p.cash = self.init_cash
                p.cash_available = self.init_cash
                p.save()
                
                for s in Game.STOCK_LIST:
                    pd = PortfolioDetail()
                    pd.portfolio = p
                    pd.stock = s
                    pd.qty = self.init_qty
                    pd.qty_available = self.init_qty
                    pd.save()
            
            Market.start(self)
    
    def end_game(self):
        if self.state == Game.RUNNING:
            self.end = datetime.datetime.now()
            self.save()

class PortfolioManager(models.Manager):
    def calculate_score(self, game, stock, price):
        return self.raw('SELECT p.*, d.stock, d.qty, p.cash + d.qty * ' + str(price) + ' as score FROM stock_portfolio p inner join stock_portfoliodetail d on p.id=d.portfolio_id where p.game_id=%s and d.stock=%s order by p.cash + d.qty * ' + str(price) + ' desc', [game.pk, stock, ])

class Portfolio(models.Model):
    game = models.ForeignKey(Game)
    email = models.CharField(max_length=50)
    cash = models.DecimalField(decimal_places=2, max_digits=12, default=0)
    cash_available = models.DecimalField(decimal_places=2, max_digits=12, default=0)
    
    objects = PortfolioManager()
    
    class Meta:
        ordering = ['email']
    
    def save(self, *args, **kwargs):
        if self.pk is None and self.game.state != Game.READY:
            raise GameException('Game has already been started.' if self.game.state == Game.RUNNING else 'Game is already ended.')
        super(Portfolio, self).save(*args, **kwargs)

class PortfolioDetailManager(models.Manager):
    
    def get_with_price(self, portfolio):
        return self.raw('SELECT d.*, m.price FROM stock_portfoliodetail d inner join stock_market m on d.stock=m.stock where d.portfolio_id=%s and m.game_id=%s order by d.id', [portfolio.pk, portfolio.game.pk])

class PortfolioDetail(models.Model):
    portfolio = models.ForeignKey(Portfolio)
    stock = models.CharField(max_length=8)
    qty = models.PositiveIntegerField(default=0)
    qty_available = models.PositiveIntegerField(default=0)
    
    objects = PortfolioDetailManager()
    
    class Meta:
        ordering = ['pk']
        
class OrderManager(models.Manager):
    
    def get_highest_bid(self, game, stock, limit_price=None):
        pending_orders = self.get_query_set().filter(game=game, type=Order.BUY, stock=stock, status=Order.PENDING)
        if limit_price:
            pending_orders = pending_orders.filter(Q(price__gte=limit_price) | Q(market_price=True))
        return pending_orders.order_by('-market_price', '-price', 'pk')
    
    def get_lowest_ask(self, game, stock, limit_price=None):
        pending_orders = self.get_query_set().filter(game=game, type=Order.SELL, stock=stock, status=Order.PENDING)
        if limit_price:
            pending_orders = pending_orders.filter(Q(price__lte=limit_price) | Q(market_price=True))
        return pending_orders.order_by('-market_price', 'price', 'pk')

class Order(models.Model):
    BUY = 1
    SELL = -1
    TYPE_CHOICES = ((BUY, 'Buy'), (SELL, 'Sell'))
    
    PENDING = 1
    COMPLETE = 2
    CANCEL = 3
    STATUS_CHOICES = ((PENDING, 'Pending'), (COMPLETE, 'Completed'), (CANCEL, 'Canceled'))
    
    MP_RESERVE_RATE = '1.2'
    
    game = models.ForeignKey(Game)
    portfolio = models.ForeignKey(Portfolio)
    type = models.SmallIntegerField(choices=TYPE_CHOICES)
    stock = models.CharField(max_length=8)
    price = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    price_reserve = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    market_price = models.BooleanField(default=False)
    qty = models.PositiveIntegerField(default=0)
    match = models.PositiveIntegerField(default=0)
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=PENDING)
    reason = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    
    objects = OrderManager()
    
    class Meta:
        ordering = ['pk']
    
    
    def save(self, *args, **kwargs):
        if self.pk is None and self.game.state != Game.RUNNING:
            raise GameException('Game has not been started yet.' if self.game.state == Game.READY else 'Game is already ended.')
        
        if self.qty == self.match:
            self.status = Order.COMPLETE

        super(Order, self).save(*args, **kwargs)
        
    @transaction.commit_on_success
    def cancel(self):
        myport = self.portfolio
        mydetail = myport.portfoliodetail_set.filter(stock=self.stock)[0]
        
        if self.type == Order.SELL:
            mydetail.qty_available += (self.qty - self.match) 
            mydetail.save()
        else:
            myport.cash_available += ((self.qty - self.match) * self.price_reserve)
            myport.save()
            
        self.status = Order.CANCEL
        self.save()

        Market.objects.get(game=self.game, stock=self.stock).update()
            
    def reserve(self):
        myport = self.portfolio
        mydetail = myport.portfoliodetail_set.filter(stock=self.stock)[0]
    
        if self.type == Order.SELL:
            mydetail.qty_available -= self.qty
            if mydetail.qty_available < 0:
                raise GameException('You do not have enough stock available.')
            mydetail.save()
        else:
            self.price_reserve = self.price if not self.market_price else Transaction.objects.get_latest_price(self.game, self.stock) * Decimal(Order.MP_RESERVE_RATE)
            myport.cash_available -= (self.qty * self.price_reserve)
            if myport.cash_available < 0:
                raise GameException('You do not have enough money.')
            myport.save()
        
        self.match = 0
        self.save()

    def resolve(self, transaction):
        myport = self.portfolio
        mydetail = myport.portfoliodetail_set.filter(stock=self.stock)[0]
        
        transaction_value = transaction.qty * transaction.price
        
        if self.type == Order.SELL:
            myport.cash += transaction_value
            myport.cash_available += transaction_value
            myport.save()
            
            mydetail.qty -= transaction.qty
            mydetail.save()
        else:
            myport.cash -= transaction_value
            myport.cash_available += ((self.price_reserve * transaction.qty) - transaction_value)
            myport.save()
            
            mydetail.qty += transaction.qty
            mydetail.qty_available += transaction.qty
            mydetail.save() 
            
        self.match += transaction.qty
        self.save()

    @transaction.commit_on_success
    def place_order(self):
        self.reserve()
        
        if self.type == Order.SELL:
            options = Order.objects.get_highest_bid(self.game, self.stock, self.price if not self.market_price else None)
        else:
            options = Order.objects.get_lowest_ask(self.game, self.stock, self.price if not self.market_price else None)

        qty_pending = self.qty - self.match
        for o in options:
            offer_qty = o.qty - o.match
            match_qty = min(qty_pending, offer_qty)

            qty_pending -= match_qty

            log = Transaction()
            log.game = self.portfolio.game
            log.stock = self.stock
            
            if self.type == Order.SELL:
                log.seller = self
                log.buyer = o
            else:
                log.seller = o
                log.buyer = self

stock/templates/stock/admin.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% load staticfiles %}
{% load humanize %}
<title>Stock trading game - Admin view</title>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="all" />

<script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
<script src="{% static 'js/angular.min.js' %}"></script>
<script src="{% static 'js/angular-cookies.min.js' %}"></script>
<script src="{% static 'js/angular-resource.min.js' %}"></script>
<script src="{% static 'stock/js/app-stock.js' %}"></script>
</head>
<body ng-app="stockApp">
<section class="container">
	<h1>Welcome to Stock Trading game!</h1>
	<div class="panel panel-default" style="width:500px; margin:100px auto 0;">
		<div class="panel-heading">
			<h3 class="panel-title">Please log in</h3>
		</div>
		<div class="panel-body">
			<form action="{% url 'stock:admin' %}" method="post" role="form" class="form-inline">
				{% csrf_token %}
				<input name="username" placeholder="username" type="text" class="form-control" />
				<input name="password" placeholder="password" type="password" class="form-control" />
				<button class="btn btn-default">Submit</button>
				{% if error %}<p class="text-danger">{{error}}</p>{% endif %}
			</form>
		</div>
	</div>
</section>
</body>
</html>

stock/templates/stock/admin_game_form.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% load staticfiles %}
<title>Stock trading game</title>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="all" />

<script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
<script src="{% static 'js/angular.min.js' %}"></script>
<script src="{% static 'js/angular-cookies.min.js' %}"></script>
<script src="{% static 'js/angular-resource.min.js' %}"></script>
<script src="{% static 'stock/js/app-stock.js' %}"></script>
</head>
<body ng-app="stockApp">
<header>
	{% csrf_token %}
</header>
<section class="container" ng-controller="stockAdminController">
	<h1>Game Settings</h1>
	{% verbatim %}
	<div class="alert alert-info" ng-if="!form.pk">Create a new game.</div>
	<form class="form-horizontal" role="form" ng-submit="save()">
		<div class="panel panel-default">
			<div class="panel-heading form-inline">
				<h4>Game Setting: <input class="form-control" type="text" placeholder="Name" ng-model="form.name" style="width:200px" /></h4>
			</div>
			<div class="panel-body">
				<div class="col-md-4">
					<h4>Session Settings</h4>
					<div class="form-group">
						<label class="col-sm-5 control-label">Password</label>
						<div class="col-sm-6"><input class="form-control" type="text" placeholder="Password" ng-model="form.password" required /></div>
					</div>
					<div class="form-group">
						<label class="col-sm-5 control-label">Session length</label>
						<div class="col-sm-6"><input class="form-control" type="number" min="10" step="5" placeholder="minutes" ng-model="form.period" /></div>
					</div>
				</div>
				<div class="col-md-4">
					<h4>User Settings</h4>
					<div class="form-group">
						<label class="col-sm-5 control-label">Initial Cash</label>
						<div class="col-sm-6"><input class="form-control" type="text" placeholder="Cash" smart-float  ng-model="form.init_cash" /></div>
					</div>
				</div>
				<div class="col-md-4">
					<h4>Stock Settings (A-J)</h4>
					<div class="form-group">
						<label class="col-sm-5 control-label">Initial Price</label>
						<div class="col-sm-6"><input class="form-control" type="text" placeholder="Price" smart-float ng-model="form.init_price" /></div>
					</div>
					<div class="form-group">
						<label class="col-sm-5 control-label">Initial QTY</label>
						<div class="col-sm-6"><input class="form-control" type="number" placeholder="QTY" min="0" ng-model="form.init_qty" /></div>
					</div>
				</div>
				<p class="text-center text-danger">{{error_msg}}</p>
				<p class="text-center"><button class="btn btn-lg btn-primary">Save</button></p>
			</div>
		</div>
	</form>
	{% endverbatim %}
</section>
<footer>
	
</footer>
<script>
stockApp.controller('stockAdminController', ['$scope', '$http', '$window', 'gameSvc', function($scope, $http, $window, gameSvc) {
	
	$scope.form = {{game|safe}};
	
	$scope.save = function() {
		gameSvc.save(null, $scope.form, function(value) {
			$window.location = "{% url 'stock:admin_game_list' %}";
		}, function(httpResponse) {
			$scope.error_msg = httpResponse.data;
		});
	}
	
}]);

</script>
</body>
</html>

stock/templates/stock/admin_game_list.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% load staticfiles %}
{% load humanize %}
<title>Stock trading game - Admin view</title>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="all" />

<script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
<script src="{% static 'js/angular.min.js' %}"></script>
<script src="{% static 'js/angular-cookies.min.js' %}"></script>
<script src="{% static 'js/angular-resource.min.js' %}"></script>
<script src="{% static 'stock/js/app-stock.js' %}"></script>
</head>
<body ng-app="stockApp">
<section class="container" ng-controller="gameController">
	<h1>Welcome to Stock Trading game!</h1>
	{% verbatim %}
	<nav class="navbar navbar-default" style="background-color: #d9edf7;border-color: #bce8f1;color: #31708f;">
		<p class="navbar-text" ng-if="game_active_count==0" style="color: #31708f;">There is no active game session right now.</p>
		<form class="navbar-form">
			<a href="{{game_url}}/create" class="btn btn-default">Create New Game</a>
			<div class="checkbox pull-right" style="padding-left: 10px; line-height: 34px;">
				<label><input type="checkbox" ng-model="show_all" /> Show All Game</label>
			</div>
		</form>
	</nav>
	<div class="panel" ng-class="game.style" ng-repeat="game in game_list track by game.pk" ng-controller="gameItemController">
		<div class="panel-heading">
			<div class="pull-right">
				<button class="btn btn-default" type="button" ng-click="deleteGame(game)" ng-if="game.state==GAME_END"><span class="glyphicon glyphicon-trash"></span></button>
				<button class="btn btn-default" type="button" ng-click="openMarketBoardTable(game)">Open Market (Tabular)</button>
				<button class="btn btn-default" type="button" ng-click="openMarketBoard(game)">Open Market (Graph)</button>
			</div>
			<h4>Game Settings: {{game.name}} <small><a href="{{game_url}}/{{game.pk}}/edit" ng-if="game.state==GAME_READY">Edit</a></small></h4>
		</div>
		<div class="panel-body form-horizontal">
			<div class="row">
				<div class="col-md-3">
					<h4>Session Settings</h4>
					<div class="form-group">
						<label class="col-sm-7 control-label">Session Password</label>
						<div class="col-sm-5"><p class="form-control-static">{{game.password}}</p></div>
					</div>
					<div class="form-group">
						<label class="col-sm-7 control-label">Session length</label>
						<div class="col-sm-5"><p class="form-control-static">{{game.period|number}} mins.</p></div>
					</div>
				</div>
				<div class="col-md-3">
					<h4>User Settings</h4>
					<div class="form-group">
						<label class="col-sm-7 control-label">Initial Cash</label>
						<div class="col-sm-5"><p class="form-control-static">{{game.init_cash|currency}}</p></div>
					</div>
					<div class="form-group">
						<label class="col-sm-7 control-label"><a ng-click="toggleUser(game)"><span class="glyphicon glyphicon-info-sign"></span></a> Total User</label>
						<div class="col-sm-5"><p class="form-control-static">{{game.portfolio_count|number}}</p></div>
					</div>
				</div>
				<div class="col-md-3">
					<h4>Stock Settings (A-J)</h4>
					<div class="form-group">
						<label class="col-sm-7 control-label">Initial Price</label>
						<div class="col-sm-5"><p class="form-control-static">{{game.init_price|currency}}</p></div>
					</div>
					<div class="form-group">
						<label class="col-sm-7 control-label">Initial QTY</label>
						<div class="col-sm-5"><p class="form-control-static">{{game.init_qty|number}}</p></div>
					</div>
				</div>
				<div class="col-md-3 text-right">
					<p ng-if="game.state==GAME_READY"><button type="button" ng-click="startGame(game)" class="btn btn-lg btn-primary">Start Game</button></p>
					<p ng-if="game.state==GAME_READY" class="text-warning">Please ensure that all users are connected before starting the game</p>
					<p ng-if="game.state==GAME_RUNNING">Started on {{game.start|date:'h:mm:ss a'}}</p>
					<p ng-if="game.state==GAME_RUNNING"><button type="button" ng-click="stopGame(game)" class="btn btn-lg btn-danger">End Game</button></p>
					<p ng-if="game.state==GAME_END">
						<span class="label label-danger">Game Ended</span><br/>
					</p>
				</div>
			</div>
		</div>
		<div class="panel-body" ng-show="game.show_user && game.user_list.length > 0">
			<div class="well">
				<h4 style="margin-top:0">Joined User</h4>
				<div class="row">
				<ol>
					<li class="col-md-3" ng-repeat="user in game.user_list track by user.pk">{{user.email}}</li>
				</ol>
				</div>
			</div>
		</div>
	</div>
	{% endverbatim %}
</section>
<footer>
	
</footer>
<script>
stockApp.controller('gameController', ['$scope', '$window', '$interval', 'gameSvc', function($scope, $window, $interval, gameSvc) {
	
	$scope.poll_rate = 2000;
	
	$scope.market_url = '{% url "stock:market_base" %}';
	$scope.game_url = '{% url "stock:admin_game_list" %}';
	$scope.GAME_READY = {{READY}};
	$scope.GAME_RUNNING = {{RUNNING}};
	$scope.GAME_END = {{END}};
	
	$scope.show_all = false;
	$scope.game_list = [];
	$scope.game_active_count = 0;
	
	$scope.loadGame = function() {
		gameSvc.query( $scope.show_all? null: {'game_pk':'active'} , function(value) {
			$scope.game_active_count = 0;
			angular.forEach(value, function(game, index) {
				if (index < $scope.game_list.length) {
					angular.extend($scope.game_list[index], game);
				} else {
					$scope.game_list[index] = game;
				}
				switch (game.state) {
				case {{READY}}:
					$scope.game_list[index].style = 'panel-default'; 
					$scope.game_active_count++;
				break;
				case {{RUNNING}}:
					$scope.game_list[index].style = 'panel-success';
					$scope.game_active_count++;
				break;
				case {{END}}:
					$scope.game_list[index].style = 'panel-danger'; 
				break;
				}
			});
			$scope.game_list.length = value.length;
		});
	};
	
	$scope.startGame = function(game) {
		gameSvc.save({game_pk:game.pk, action:'start'}, null, function(value) {
			$scope.loadGame();
			$scope.openMarketBoard(game);
		});
	};
	
	$scope.stopGame = function(game) {
		gameSvc.save({game_pk:game.pk, action:'end'}, null, function(value) {
			$scope.loadGame();
		});
	};
	
	$scope.deleteGame = function(game) {
		gameSvc.save({game_pk:game.pk, action:'delete'}, null, function(value) {
			$scope.loadGame();
		});
	};
	
	$scope.toggleUser = function(game) {
		if (game.show_user)
			game.show_user=false;
		else
			game.show_user=true;
	};
	
	$scope.loadUser = function(game) {
		gameSvc.query({game_pk:game.pk, action:'portfolio'}, function(value) {
			game.user_list = value;
		});
	};
	
	$scope.openMarketBoard = function(game) {
		$window.open($scope.market_url + "/" + game.pk);
	};
	
	$scope.openMarketBoardTable = function(game) {
		$window.open($scope.market_url + "/" + game.pk + "/table");
	};
	
	$scope.$watch('show_all', function(newValue) {
		$scope.loadGame();	
	});
	
	$interval(function() {
		$scope.loadGame();	
	}, $scope.poll_rate);
	
}]);
stockApp.controller('gameItemController', ['$scope', '$window', '$interval', 'gameSvc', function($scope, $window, $interval, gameSvc) {
	$scope.$watch('game.portfolio_count + game.show_user', function(newValue) {
		if ($scope.game.show_user) {
			$scope.loadUser($scope.game);
		}
	});
}]);
</script>
</body>
</html>

stock/templates/stock/client.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% load staticfiles %}
<title>Stock trading game - Client Login</title>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="all" />

<script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
<script src="{% static 'js/angular.min.js' %}"></script>
<script src="{% static 'js/angular-cookies.min.js' %}"></script>
<script src="{% static 'js/angular-resource.min.js' %}"></script>
<script src="{% static 'stock/js/app-stock.js' %}"></script>
</head>
<body>
	<section class="container">
		<h1>Welcome to Stock Trading game!</h1>
		{% if not game_list %}
			<div class="alert alert-info">There is no active game session right now. Please try again later. <a href="javascript:window.location.reload()" class="btn btn-default">Refresh</a></div>
		{% else %}
			<form action="{% url 'stock:client' %}" method="post" role="form" class="form-inline">
				<div class="panel panel-default" style="width:500px; margin:100px auto 0;">
					<div class="panel-heading">
						<h3 class="panel-title">Join game</h3>
					</div>
					<div class="panel-body">
						{% csrf_token %}
						<input name="email" placeholder="email" type="email" class="form-control" />
						<input name="password" placeholder="session password" type="password" class="form-control" />
						<button class="btn btn-default">Submit</button>
						{% if error %}<p class="text-danger">{{error}}</p>{% endif %}
					</div>
				</div>
			</form>
		{% endif %}
	</section>
</body>
</html>

stock/templates/stock/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% load staticfiles %}
<title>Stock trading game</title>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="all" />

<script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
<script src="{% static 'js/angular.min.js' %}"></script>
<script src="{% static 'js/angular-cookies.min.js' %}"></script>
<script src="{% static 'js/angular-resource.min.js' %}"></script>
<script src="{% static 'stock/js/app-stock.js' %}"></script>
</head>
<body>
<section class="container">
	<h1>Welcome to Stock Trading game!</h1>
	{% if game == None %}
	<div class="alert alert-info">There is no active game session right now. Please try again later.</div>
	{% else %}
	<script>
		window.location.href = "{% url 'stock:client' %}";
	</script>
	{% endif %}
</section>
</body>
</html>

stock/templates/stock/score.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% load staticfiles %}
<title>Stock trading game - Score</title>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="all" />
<style>
	span.up {
		display: inline-block; width: 0; height: 0;
		border: 6px solid green;
		border-top:0;
		border-left-color: transparent;
		border-right-color: transparent;
	}
	span.down {
		display: inline-block; width: 0; height: 0;
		border: 6px solid red;
		border-bottom:0;
		border-left-color: transparent;
		border-right-color: transparent;
	}
</style>
<script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
<script src="{% static 'js/angular.min.js' %}"></script>
<script src="{% static 'js/angular-cookies.min.js' %}"></script>
<script src="{% static 'js/angular-resource.min.js' %}"></script>
<script src="{% static 'stock/js/app-stock.js' %}"></script>
</head>
<body>
<section class="container">
	<h1 class="pull-left">Score Board - {{game.name}}</h1>
	<table class="table table-bordered table-condensed">
		<thead>
			<tr>
				<th>Email</th>
				<th>Cash</th>
				<th>Stock</th>
				<th>QTY</th>
				<th>Score</th>
			</tr>
		</thead>
		<tbody>
			{% for port in portfolio_list %}
			<tr>
				<td>{{port.email}}</td>
				<td>{{port.cash}}</td>
				<td>{{port.stock}}</td>
				<td>{{port.qty}}</td>
				<td>{{port.score}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</section>
</body>
</html>